
package com.jws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Jws", targetNamespace = "http://jws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Jws {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "manualExtractData", targetNamespace = "http://jws.com/", className = "com.jws.ManualExtractData")
    @ResponseWrapper(localName = "manualExtractDataResponse", targetNamespace = "http://jws.com/", className = "com.jws.ManualExtractDataResponse")
    @Action(input = "http://jws.com/Jws/manualExtractDataRequest", output = "http://jws.com/Jws/manualExtractDataResponse")
    public void manualExtractData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SelectHzGisTpsZrz")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SelectHzGisTpsZrz", targetNamespace = "http://jws.com/", className = "com.jws.SelectHzGisTpsZrz")
    @ResponseWrapper(localName = "SelectHzGisTpsZrzResponse", targetNamespace = "http://jws.com/", className = "com.jws.SelectHzGisTpsZrzResponse")
    @Action(input = "http://jws.com/Jws/SelectHzGisTpsZrzRequest", output = "http://jws.com/Jws/SelectHzGisTpsZrzResponse")
    public String selectHzGisTpsZrz(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectHzFwdjTpfJcdjb", targetNamespace = "http://jws.com/", className = "com.jws.SelectHzFwdjTpfJcdjb")
    @ResponseWrapper(localName = "selectHzFwdjTpfJcdjbResponse", targetNamespace = "http://jws.com/", className = "com.jws.SelectHzFwdjTpfJcdjbResponse")
    @Action(input = "http://jws.com/Jws/selectHzFwdjTpfJcdjbRequest", output = "http://jws.com/Jws/selectHzFwdjTpfJcdjbResponse")
    public String selectHzFwdjTpfJcdjb(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectHzGisTpsFw", targetNamespace = "http://jws.com/", className = "com.jws.SelectHzGisTpsFw")
    @ResponseWrapper(localName = "selectHzGisTpsFwResponse", targetNamespace = "http://jws.com/", className = "com.jws.SelectHzGisTpsFwResponse")
    @Action(input = "http://jws.com/Jws/selectHzGisTpsFwRequest", output = "http://jws.com/Jws/selectHzGisTpsFwResponse")
    public String selectHzGisTpsFw(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
